### ISSUE TITLE
Cursor disappears while clicking on devtools-like tCP

### ISSUE THREAD

**Issue by ghost** [PitPik/tinyColorPicker#1]
Hi @PitPik ;)

If I try http://www.dematte.at/tinyColorPicker/?type=dev_skinned#demo 
and click somewhere not at inputs (e.g. while trying to copy rgb code, or just in the gaps), the cursor disappears and is visible only after the mouse button is released.
Other modes work great though :)

Also, a little enhancement proposal: It would be cool if user could specify which palette element to replace. For now the palette is just a queue :( And I believe, as arrow (`<`) points to the most right square, colors should appear from the right :stuck_out_tongue_closed_eyes:

**Comment by PitPik** [comment]
Hi @ct-js 
thanks for the feedback!
Well, the demos are supposed to show how easy it is to add stuff to the color picker and prove the flexibility,... not necessarily to deliver full featured color pickers.
@ cursor: The fact that the mouse disappears is actually done on purpose
`.cp-color-picker:active { cursor:none; }`
...but maybe this causes too much confusion?!! Maybe it's better to only do this on `.cp-xy-slider`.
Other than that, copying and selecting still works (just the cursor doesn't show...)
@ color palette: I'll change the arrow to an 'S' (for save), also less confusion then (i guess ;o)
And as I said, I tried to keep it simple so people can easier see how it works...

Thank you very much for your contributions,
Cheers

**Comment by ghost** [comment]
As for me, cursor mustn't be hidden at all - at least, if nothing can represent it (like the circle of the picked color on color patch). If I can't find the cursor, panic begins 😱😃 You know, cursor is like hands...

Will try out your tCP soon; gonna make some experiments with it =_= 

-----Исходное сообщение-----
От: "Peter Dematté" notifications@github.com
Отправлено: ‎04.‎02.‎2015 22:31
Кому: "PitPik/tinyColorPicker" tinyColorPicker@noreply.github.com
Копия: "ct.js" aeonix@mail.ru
Тема: Re: [tinyColorPicker] Cursor disappears while clicking ondevtools-like tCP (#1)

Hi @ct-js 
thanks for the feedback!
Well, the demos are supposed to show how easy it is to add stuff to the color picker and prove the flexibility,... not necessarily to deliver full featured color pickers.
@ cursor: The fact that the mouse disappears is actually done on purpose
.cp-color-picker:active { cursor:none; }
...but maybe this causes too much confusion?!! Maybe it's better to only do this on .cp-xy-slider.
Other than that, copying and selecting still works (just the cursor doesn't show...)
@ color palette: I'll change the arrow to an 'S' (for save), also less confusion then (i guess ;o)
And as I said, I tried to keep it simple so people can easier see how it works...
Thank you very much for your contributions,
Cheers
