### ISSUE TITLE
Maybe viewport position bug?

### ISSUE THREAD

**Issue by Daijobou** [PitPik/tinyColorPicker#10]
I have change the height of my browser window
http://picload.org/image/cwirral/colorpickerb.png
see blue border left/bottom then I click on input field and the colorPicker is over the input field. Its not much better to set position that colorPicker is above the input field?

Like http://picload.org/image/cwirrli/colorpickerc.png
the red rectangle is the new browser window, and set the box above the input field, when its possible.

**Comment by PitPik** [comment]
I tried to keep colorPicker as small as possible and as open as possible. My intention was to keep the color picker inside the view port and it dynamically moves with the resize of the view port or the scrolling. Positioning like you said is another approach, also very good or even better, but I decided for the other one. To cover too many possibilities would blow up the size of the app.
Color picker is very open in it's possibilities that you can program this yourself: In your `renderCallback` you have access to `toggled` which delivers `true` for 'just opened', `false` for 'just closed' or something else if none of the two. As `this` gives you the instance with some information and `$elm` with the current input field, you can calculate the position of your color picker yourself (You might to turn off animation though and make your own or just drop it...)

**Comment by Daijobou** [comment]
I agree. Maybe, you can add this feature for jquer-ui users?: http://jqueryui.com/position/ ;)
