### ISSUE TITLE
Change focus not update input field background-color

### ISSUE THREAD

**Issue by Daijobou** [PitPik/tinyColorPicker#12]
Go to https://github.com/PitPik/tinyColorPicker click in first input field, change color with keyboard and press tab-key. The background-color of first input field will not update.

**Comment by PitPik** [comment]
This is no bug, but definitely worth mentioning. I put this information in the demo section...
Thanks for the hint and for your participation.

**Comment by PitPik** [comment]
The new commit takes care of this. The default if left empty is now #FFFFFF and doesN#t cause errors any more.

**Comment by Daijobou** [comment]
Perfect!  :+1:
