### ISSUE TITLE
Colors is not defined

### ISSUE THREAD

**Issue by stefan1294** [PitPik/tinyColorPicker#13]
Getting the error "Colors is not defined" in the last line of jqColorPicker.js 
 })(window.jQuery, Colors);

**Comment by PitPik** [comment]
Hi there,
you obviously don't use the minified version, therefore you need to load color.js before jqColorPicker.js then you're fine. In jqColorPicker.min.js you find both components in one...

Good luck!

**Comment by stefan1294** [comment]
Oops. My bad. I'm terribly sorry!

**Comment by PitPik** [comment]
No problem ;o)
