### ISSUE TITLE
Question to file size

### ISSUE THREAD

**Issue by Daijobou** [PitPik/tinyColorPicker#14]
Good work! Best color-picker i know. ;)

Readme https://github.com/PitPik/tinyColorPicker/blob/master/README.md said:

```
.... This 4.7KB small (1 .js file only; ....
```

Why 4.7KB? 
Here https://github.com/PitPik/tinyColorPicker/blob/master/jqColorPicker.min.js is 10.849 kb

I think you mean color-picker alone(?), but colors.js is required and must included in this single file.

**Comment by PitPik** [comment]
Hi @Daijobou 
well, you're right, it's a bit confusing (and README.md isn't up to date). The minified version is 10.something but from the server you get it for 4.9KB. So 4.7 was before some changes I made and I forgot to update...
But thanks for pointing out. I'll make it less confusing.

Cheers
Peter

**Comment by Daijobou** [comment]
Nice. Thanks :)
