### ISSUE TITLE
Misspelled callback

### ISSUE THREAD

**Issue by Greg-123** [PitPik/tinyColorPicker#15]
Hi, I have been playing with your script...it's great...but your have the following spelling oops.

buidCallback instead of buildCallback.

I see that I am not the only one that does this.

Thanks,
Greg

**Comment by PitPik** [comment]
Hi @Greg-123 
thanks for the flowers and thanks for pointing out this issue.
I guess though you have an old copy as I fixed and updated this 12 days ago.
I also changed/fixed some other things in the meanwhile, so you might want to pull a new copy soon.

Thanks again and cheers,
Peter

**Comment by FlashJunior** [comment]
I did not see that in v1.0.0 2015-08-02. 
@PitPik I think you can close this issue.
