### ISSUE TITLE
Change()-event not working?

### ISSUE THREAD

**Issue by Daijobou** [PitPik/tinyColorPicker#16]
I have 20 inputs with colorPicker and want catch change-events and user inputs with:

```
$(document).on('change keyup', '#color1', function(){console.log($(this).val());});
```

but nothing happen in console, after change color with colorPicker. Only user inputs working.

**Comment by AidasK** [comment]
Have you solved this issue?

**Comment by Daijobou** [comment]
I use renderCallback. ;)

**Comment by AidasK** [comment]
But it is called even if value isn't changed. Please reopen this issue

**Comment by PitPik** [comment]
Hi @AidasK ,
I sut stumbled upon this 'closed' issue. Sorry that I didn't react earlier to this.
A view weeks ago I fixed this issue with the firing of events even if it doesn't change...
Just get the newest version and everything is fine.
If you have more trouble, please let me know. This time I'll answer earlier ;o)
