### ISSUE TITLE
Impossibile to set a color from another script 

### ISSUE THREAD

**Issue by nikto1** [PitPik/tinyColorPicker#18]
I've tried in many ways, but it seems to be impossibile to set a color from another script. 
[HERE](http://www.eyecon.ro/colorpicker/#implement) is an example at the bottom of the page.

Also, it's not possibile to call the  "renderCallback" twice.

I'm completly stucked......

**Comment by PitPik** [comment]
Hi @nikto1 
thanks for your interest in jqColorPicker!
Well, I can see your confusion ;) The link `http://www.eyecon.ro/colorpicker/#implement` you attached in your comment is from an other color picker,... but not mine.
jqColorPicker doesn't provide a `setColor` method. You set the color by providing the input field with a value and then call the initialization routine `$('.color').colorPicker()`.

If you want to set a color of a specific input field, first set the value `$('#myInputField').val('#FF0000')` (or something like this) and then call `$('.color').colorPicker()` again. I wouldn't recommend this though, but it's possible.

Your second question: You can set options the first time you call `$('.color').colorPicker({...})` but not a second time. If you need additional features for a second set you call, use a back door like:

```
var callCallBack = function(){};

$('.color').colorPicker({
    renderCallback: function($elm, toggled) {
        // do something here...
        callCallBack($elm, toggled);
    }
})
```

If you now need to do some more things in your callback, you can overwrite your empty `callCallBack` function.
If you want to do it right you should use javaScript's main feature: events!

```
$('.color').colorPicker({
    renderCallback: function($elm, toggled) {
        $(document).trigger('renderCallback', [ this, $elm, toggled ]);
    }
})
```

Now you can attach event listeners as many as you want (later on in your code):

```
$(document).on('renderCallback', function(event, instance, $elm, toggled){
    // do something here...
});
```

Good luck and let me know if it works for you. If you need more features then you might want to use https://github.com/PitPik/colorPicker, the big brother of jqColorPicker...
Cheers,
Peter

**Comment by nikto1** [comment]
Hi Peter,

thanks for reply, very gently.
I attacked the link to the other colorPicker just to give an example :-)

Here's a short explanation what I'm trying to achive:

I call the colorpicker a first time to initialize the script. Inside the callback there's a function to modify the colors of a WP theme dynamically. When the user have finished with his modification, he could save them in an css file, created via php/ xml.

Once the css file is saved, you could modify it, selecting it through an select box. If you select a saved css file, all the colors of the theme and the respective input fields in the control panel changes their colors.

But then, if i click on an input field, the colorpicker doesn't react to the second callback. In other words, i tryed to initialize the colorpicker + callback a second time to set the appropriate color in the colorpicker from the input fields an not viceversa, but it's not working.

So i gave you the link as an example. Is it possibile somehow to set a color in the colorpicker from an input field; e.g. setColor(), and call this function from another script? 

I've tried also to modify the colorpicker script for 2 days but no luck, because primarily i write php so i do not understand completely the javascript logic.

I really would like to use it, because it's very lightweight and fast.

Greetings and thanks again 
Leonardo

**Comment by PitPik** [comment]
@nikto1 
did you have any success yet with my instructions?
I guess the easies would be the one where you overwrite your 'external' callback the second time you initialize it (the callCallBack example), so the first time you say:

``` javascript
var callCallBack = function($elm, toggled) {
    //... whatever you need the first time
};

$('.color').colorPicker({
    renderCallback: function($elm, toggled) {
        callCallBack.call(this, $elm, toggled);
    }
})
```

...where you define `callCallBack` with what you need the first time...
and the second time you would call colorpicker you just overwrite the callback:

``` javascript
callCallBack = function($elm, toggled) {
    //... whatever you need the second time
};
$('.color').colorPicker(); // If your colors changed here
```

**Comment by nikto1** [comment]
I follow your instructions, modied my code (merge some .js files) but still without luck :-((

My .js structure is:

```
 // CODE
 // Here i call the colorPicker with the callback var inside
 // other code
 // HERE comes an AJAX CALL and inside there should be something like
 $(this).ColorPicker(event.val);  // just for example 
 // where $(this) are each input field and event.val are the values from where the
 //  fields value should set the colors in the colorpicker
```

 The problem is that the ajax call comes +/- 200 lines below the init call for the colorPicker; Also, i cannot declare the 

```
  var callCallBack
```

outside the ajax call because i need it inside (i think, but no idea).

Still stucked but thanks a lot for the support.

**Comment by PitPik** [comment]
Your problem here is that you can't set the colors by passing variables via colorPicker, you should first set the values of the input fields and then call colorPicker (without parameters) again, so:

``` javascript
$(this).each(function(index, element) { // if that $(this) are the input fields...
    $(element).val( /* here you set the value */ ); // ???
}).colorPicker(); // ...and here you initialize the newly set input fields again.
```

I don't exactly know how you get the single values and where `event.val` comes from (for your input fields), I guess it should be an array or an object) so the line `$(elm).val(...)` might look different in your case.

Your second concern: You can declare `var callCallBack` outside for the first time and then redeclare it (without `var` though) inside your ajax callback, that's perfectly ok...

...and also, be aware that it's `.colorPicker()` not `.ColorPicker()` (c not C)

Let me know if you get any further...

**Comment by PitPik** [comment]
Well, I now I guess I know how it works... does your `$(index)...` come from an each loop already? I f so then you should just put:

``` javascript
    $(this).val(event.val);
```

and then outside this each loop the `.colorPicker();` on the input collection again.
Well, it's really hard to guess code ;o)

**Comment by nikto1** [comment]
Sent you a mail at  github[at]dematte[dot]at with part of my code. I hope this will clear the things.

Thank you really very much!

**Comment by nikto1** [comment]
I tried with

    $(this).val(event.val);

like you said for the second time, but i am still missing something on redeclaring the second callback in the ajax part

**Comment by nikto1** [comment]
If i'm trying to set the colorpicker a second time i always get a

      Uncaught Error: Syntax error, unrecognized expression: '.color','.color'...eccc

each time i click the input field

**Comment by nikto1** [comment]
Finally i think i figured it out, without a second callback:

The first time i called the colorPicker normally configuring it
But the second time is:

``` javascript
         $('.color').colorPicker({
     renderCallback: function($elm, toggled) { 
         $(this).val(event.val);
    }
    });
```

Please let me know if it's a big problem if the colorPicker is initialized a second time in the ajax call. I coudn't figure it out with the callbacks.
Above that your help is/ was vital.
