### ISSUE TITLE
Not showing current values on rgb text-box

### ISSUE THREAD

**Issue by nglatest** [PitPik/tinyColorPicker#19]
I tried to use sample from 'plugin.input' which was provided as sample in index,js. After that it showed me that rgb text-boxes but values are nil. It also not shows any values there if I move the sliders inside the picker. 
Second thing it also loads jqColorPicker.js.map. Total upload size comes out to 27kb instead of 4kb as mentioned in the site.

Screenshot is attached.
![colorpick issue](https://cloud.githubusercontent.com/assets/11812833/7000452/fdddfc10-dbf0-11e4-93e4-1b8aff19ba3e.png)

**Comment by PitPik** [comment]
Hi @nglatest 
thanks for your interest and contribution.
Well, it's hard to guess an error if I don't see any code or error log... I see from the picture that you disabled alpha (`opacity: false`) and therefore the hex input field also doesn't show, but this shouldn't make any difference. I do see though that you have '304 Not Modified'... you might want to enable `Disable cache (while DevTools is open)` in your Chrome's Debug-Tool Settings to always get the fresh modified javaScript files. If this doesn't help either, make a jsFiddle so I can have a look at it.

To the second point (.map): This is a feature for developers (supported by Chrome and other browsers these days). The file jqColorPicker.min.js has a comment on the bottom: `//# sourceMappingURL=jqColorPicker.js.map`. This is information for the browser to make it possible to see the source code of jqColorPicker.min.js even though it is minified (In the 'Sources Tab' of Chrome Dev-Tools). This file will only load though if your Dev-Tools are open. For your client who uses the browser just in a normal way, this file won't load. If you don't want this to happen anyhow and don't mind that .min.js files show cryptic then delete the last line (the comment) in your .min.js file.

Good luck and cheers,
Peter

**Comment by DevinCarl** [comment]
for the first issue, I found it may casued by the below code missing of  'plugin.input': 

renderCallback: function($elm, toggled) {
    var colors = this.color.colors.RND,
    modes = {
        r: colors.rgb.r, g: colors.rgb.g, b: colors.rgb.b,
        h: colors.hsv.h, s: colors.hsv.s, v: colors.hsv.v,
        HEX: this.color.colors.HEX
    };
    $('input', '.cp-panel').each(function() {
        this.value = modes[this.className.substr(3)];
    });
}
