### ISSUE TITLE
ReferenceError: Can't find variable: Colors

### ISSUE THREAD

**Issue by bappe** [PitPik/tinyColorPicker#2]
Hi,

I am trying out the tinyColorPicker, but I don't seem to get it to work.

Basically, I am only loading jQuery and then jqColorPicker.js.

However, when trying to bind the plugin to a number of input fields with class "colorpicker", it throws the following error:
ReferenceError: Can't find variable: Colors

Note that I did not include colors.js yet, since you wrote on your homepage that only one file is needed.

Thanks!

/b

**Comment by PitPik** [comment]
Hi @bappe 
well, if you use jqColorPicker.js you also have to use colors.js before, but if you use jqColorPicker.min.js then everything is taken care of...

Good luck,
Peter
