### ISSUE TITLE
Optimize the position of the ColorPicker

### ISSUE THREAD

**Issue by DevinCarl** [PitPik/tinyColorPicker#20]
Currently it will cover the input if it's near the bottom as below.
![image](https://cloud.githubusercontent.com/assets/11863678/7111768/e01b6220-e1f5-11e4-8dce-133cf354213a.png)

so I modified the function "toggle(event)" (line: 86) to make it better.
'top': (_$UI[0]._top = position.top + $this.outerHeight()) -
    ((_$UI[0]._top = _$UI[0]._top + _$UI[0]._height -
    ($window.scrollTop() + $window.height())) + gap > 0 ?
    (_$UI[0]._top + gap) < _$UI[0]._height ? _$UI[0]._height + $this.outerHeight() + gap: _$UI[0]._top + gap : 0)
![image](https://cloud.githubusercontent.com/assets/11863678/7111742/ad1a06ba-e1f5-11e4-90e6-45cfb08920de.png)

but I have one doubt, in the package, the file "jqColorPicker.min.js" is combined by "colors.js" and "jqColorPicker.js" , right?
If yes,  why after I combined them manually and used "uglifyjs2" to minify, the result file size(16K) is still bigger than your  "jqColorPicker.min.js"(11K)?

**Comment by Daijobou** [comment]
I use this http://closure-compiler.appspot.com/home

Original Size: 7.07KB gzipped (22.7KB uncompressed)
Compiled Size: 4.42KB gzipped (10.42KB uncompressed)

**Comment by PitPik** [comment]
Hi @DevinCarl,
finally I do have a solution for you:
There is a new callback `positionCallback` that you can use to position your colorPicker wherever you want; on toggle and on scroll. See the demo `./demo/index.js` on how it works.
Good luck
