### ISSUE TITLE
Doesn't operate well with jQuery UI

### ISSUE THREAD

**Issue by Ximore** [PitPik/tinyColorPicker#21]
I have tried to use this plugin in combination with a simple CMS system. I can call the function $('.color').colorPicker(); without any issues, and I am still able to drag and drop elements in the CMS but when I simply click the input field and close the color select again, the sortable, draggable and droppable features are no longer working. The elements simply losses functionality.

**Comment by PitPik** [comment]
Hi @Ximore 
thanks for pointing out...
Well, when you call `$('.color').colorPicker();` nothing happens so far as I intended to save memory. I just install some event listeners on `$(document.body)`, and I actually name-space them to not interfere with anything... The first time you click on a field, the HTML of the color picker gets appended to the body and there I install some more event listeners (to the color picker). That's quit all that happens...

Could you do me a favor and try adding `body: '#someID'` to your options and rename `#someID` to a valid selector in your scenario where a `<div id="someID">` (or whatever) is holding all your input fields.
Either way, if it works or not I would have an idea what could be wrong...

Cheers,
Peter

**Comment by Ximore** [comment]
I tried something as simple to append this html to your index.html page.

```
<div>
    <ul id="dims">
        <li>item 1</li>
        <li>item 2</li>
        <li>item 3</li>
        <li>item 4</li>
        <li>item 5</li>
    </ul>
</div>
```

And then I appended this in the bottom:

```
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"></script>
<script>
    $('#dims').sortable();
</script>
```

From the beginning I can sort the listed items, but once I have used any of the color inputs, it looses it functionality.

**Comment by PitPik** [comment]
I'm experiencing the same trouble here. I will take a look at it.

**Comment by PitPik** [comment]
I fixed the problem! It was indeed an event handler problem. With the new version this is fixed...
Good luck!

**Comment by Ximore** [comment]
Great! thanks.. I will check it out.. Thanks for quick action..
