### ISSUE TITLE
issue on IE11?

### ISSUE THREAD

**Issue by paul-cheung** [PitPik/tinyColorPicker#24]
is there a pick color issue on ie11? it's ok on ie10 and chrome, but on ie11, when i picked color, the value of the input field which binded to this colorpicker plugin, its value is "#NANNANNAN". im not sure if i use it in a wrong way, thanks for help.

the code is like below:

```
    var $colors = $('input.color').colorPicker({
        customBG: '#222',
        readOnly: true,
        init: function (elm, colors) { // colors is a different instance (not connected to colorPicker)
            elm.style.backgroundColor = elm.value;
            elm.style.color = colors.rgbaMixCustom.luminance > 0.22 ? '#222' : '#ddd';
        }
    }).each(function (idx, elm) {
        $(elm).css({ 'background-color': this.value })
    });
```

note: im using bootstrap at the same page, is that a problem?

**Comment by PitPik** [comment]
Hi @paul-cheung,
sorry for the late answer. Haven't been online for quite a long time.
I don't have this issue on IE11 but I see something strange in you setup:
'init' sets the bg-color like `elm.style.backgroundColor = elm.value;` and then you use

``` javascript
.each(function (idx, elm) {
        $(elm).css({ 'background-color': this.value })
    });
```

to do the same thing again. This could confuse color-picker (wild guess though).
I have no IE11 issue so far. Hope you find the issue.
Make sure you got the latest version though. ;o)
Peter

**Comment by paul-cheung** [comment]
Thanks Peter, I will try you solution😊😊
