### ISSUE TITLE
set color dynamically

### ISSUE THREAD

**Issue by MikeSha** [PitPik/tinyColorPicker#27]
Hi PitPik!

Your colorpicker is pretty nice and I really like it. But I have a question: how to set a color dynamically? I use 'div' variation.

Thanks!

**Comment by PitPik** [comment]
Hi @MikeSha,
Thanks for participating and your positive comments ;o)
Sorry, but I don't quite understand what you're about to do.
What do you mean by 'dynamically' and what is a 'div' variation?
Cheers
Peter

**Comment by MikeSha** [comment]
nevermind :) I've found the solution :)

2015-07-05 15:21 GMT+03:00 Peter Dematté notifications@github.com:
