### ISSUE TITLE
No destroy() method

### ISSUE THREAD

**Issue by ktktok** [PitPik/tinyColorPicker#29]
Plugin can not be used in single-page applications. Please add destroy() method.

**Comment by PitPik** [comment]
@ktktok: Thanks, good idea... will ad this
Is done already... has to be tested and will be committed soon.

**Comment by PitPik** [comment]
@ktktok $().colorPicker.destroy(); has been added in new version.
It doesn't kill everything (not HTML and CSS for even less memory usage) but it destroys all event handlers to free memory.

**Comment by ktktok** [comment]
Thank you!
