### ISSUE TITLE
TinyColorPicker box is not visible

### ISSUE THREAD

**Issue by Daijobou** [PitPik/tinyColorPicker#3]
Without set z-index:9999 hard in code the "cp-color-picker" is not visible for me. What is the best way to fix this? ;)

I add:
....H=".cp-color-picker{....;z-index:9999}.....

**Comment by PitPik** [comment]
If I take your jsFiddle examples and turn `z-index:9999` off, it still works. Don't know what's wrong. The colorPicker gets appended to the end of the document, so it should always be on top of all other things. Just make sure that you don't set other elements on some high z-index and that the html and body has a full height (100%) so positioning works fine.

**Comment by Daijobou** [comment]
Here a example http://img5.picload.org/image/cwirgaa/colorpickera.png
or http://jsfiddle.net/030j27LL/4/ click in edit.. you will not see the box.

**Comment by PitPik** [comment]
To your example in http://jsfiddle.net/030j27LL/4/: there you have `#container {z-index: 3}` which is the first child of '<body>'. `.cp-color-picker`is the second child, so it gets covered by `#container`. You also have `position: relative;` and `background:silver;`in your `#container` css declaration, and this gives the rest...
Try not to use `z-index` in your pages. This gives a lot of confusions. Different browsers even translate this differently and its hard to debug. Only use 'z-index' if its really needed.

**Comment by Daijobou** [comment]
In my code I need z-index, its in a overlay and that must be over all other elements on the page. I think my case is "special" so I close this ticket. ;)
