### ISSUE TITLE
[proposal] Bower support

### ISSUE THREAD

**Issue by spajz** [PitPik/tinyColorPicker#30]
Hi,
Nice picker. Please add support for Bower. 
Thanks

**Comment by dobromir-hristov** [comment]
Would be nice, yes.

**Comment by infomiho** [comment]
Still would be nice.

**Comment by PitPik** [comment]
Hi @spajz, @dobromir-hristov, @infomiho,

Ok, done! ;o)
`bower install tinyColorPicker`
