### ISSUE TITLE
How to move the color picker box

### ISSUE THREAD

**Issue by ghost** [PitPik/tinyColorPicker#35]
First of all I want to thank You for develop the nice and useful plugin. But now I want to modify it and want to insert .cp-color-picker div into custom container instead the body.

Is it possible ?

**Comment by PitPik** [comment]
Hi @himelkazi :
unfortunately this is not possible and tinyColorPicker won't support this by default.
Placing a popup inside a relative container always seems to cause problems (positioning, overflow: hidden, etc.). I had this with my old project [colorPicker](https://github.com/PitPik/colorPicker) but this caused too often too many trouble.
Why would you want to place it inside a container? If you tell me more about your situation, maybe I can help you with a little trick...

**Comment by PitPik** [comment]
Hi @himelkazi ,
I finally do have a solution on how to put the colorPicker inside a custom container. There is a new callback called `positionCallback` where you can actually append colorPicker where ever you need to (before it shows) and then calculate your positions where to place it...
You can see a demo in the ./demo/index.js file.
Hope this helps you.
Cheers
Peter
