### ISSUE TITLE
Callback drop code

### ISSUE THREAD

**Issue by Daijobou** [PitPik/tinyColorPicker#4]
I use this code

```
$('input.color').colorPicker({
    renderCallback: function($elm, toggled)
    {
        console.log($elm.text);
        $('#field').css('background-color', $elm.text);
    }
});
```

Now I open the box and move cursor for colors. Result in inspector(console.log) is like:

```
#1B2938
#112132

#102032

#0F2032
#0E1F32
```

You can see the empty lines? From time to time the color-code is "empty". Tested with chrome.

Change alpha value make extrem flicking the #field. The input value is always correct. :)

**Comment by PitPik** [comment]
I will have to look into this again... For now do an `if($elm.text)` in front or go for `$elm.val()` instead. It's a bit slower but works fine...

Thank you very much for all your helpful feedback. I really appreciate this and am looking forward to fixing all the issues.
Thanks again and cheers,
Peter

**Comment by PitPik** [comment]
Find answer in 'Keep changes?' ticket. It has to do with the same circumstances.
I will get rid of $elm.text one day or rename it...
