### ISSUE TITLE
How to set HEX as default color mode

### ISSUE THREAD

**Issue by declin93** [PitPik/tinyColorPicker#40]
Hello, sorry if in the documentation you wrote already how to set hex as default color mode, but i can't find how.

Thanks.

**Comment by PitPik** [comment]
Hi @declin93 ,
if your value is initially a HEX value, tinyColorPicker will do anything in HEX, just like you see it in the demo (first input field). As soon, as you change the alpha value, the colorPicker changes to rgba mode, but if you disable alpha, this won't happen. But tinyColorPicker remembers the initial type of the input field and switches back to HEX when alpha is 1 again.

**Comment by declin93** [comment]
Thanks for the fast answer!
I tried your solution but i still get a hsl value instead of HEX
even if i set the value to hex
`<input class="color no-alpha" value="#000000" type="text" name="colorCode" placeholder="RRGGBB">`
![screeshot](https://cloud.githubusercontent.com/assets/13251055/11912171/26e665ce-a631-11e5-93ca-5caa5885e9f3.png)

**Comment by PitPik** [comment]
Without your setup it's hard to tell what's going wrong...
But for now I can tell you how to force it to HEX anyhow:

``` javascript
$('.color').colorPicker({
    opacity: false, // disables opacity slider
    renderCallback: function($elm, toggled) {
        $elm.val('#' + this.color.colors.HEX);
    }
});
```

**Comment by declin93** [comment]
It Worked! Thank you!

**Comment by PitPik** [comment]
You're wellcome!!
Would you mind clicking on the ★ if you find this peace of code helpful and good ;o)
Tanks!

**Comment by darkape** [comment]
Just want to say thanks as I needed this code snippet as well! :)

(Clicked on the ★ as well.)
