### ISSUE TITLE
EDIT: Refresh colorpicker

### ISSUE THREAD

**Issue by ibsenleo** [PitPik/tinyColorPicker#44]
Hello! nice component!
Question: Is there a way to update the component (input background, etc) after modifiying the input content by code?

Initialize:

``` javascript
$('#colorpick').colorPicker();
```

Modify input:

``` javascript
$('#colorpick').val('#FF0000');
```

The value changes but the background stays.
some ideas?

**Comment by PitPik** [comment]
Hi @ibsenleo ,

there is an option `doRender`, so setting it to `false` disables the color and background-color rendering.
In `renderCallback` you can find out if the colorPicker just opened or closed and start painting your background there:

``` javascript
$('#colorpick').colorPicker({
    doRender: false,
    renderCallback: function($elm, toggled) {
        var colors = this.color.colors;

        if (toggled === false) { // hiding color picker
            $elm.css({
                'background-color': '#' + colors.HEX,
                'color': colors.rgbaMixBGMixCustom.luminance > 0.22 ? '#222' : '#ddd'
            });
        }
    }
});
```

Good luck

**Comment by ibsenleo** [comment]
Hello again!
Sorry, i re-read my question and it was not so clear. I was just wondering if there is a function that you use for force to "refresh" the component once you change the text input value.

Anyways, with your code i could adapt mine to make it work. Just wandering...

By the way, I have 3 textbox working with colorpicker. Want to know if every one is independent instance or they use the same instance of the component internally?

Thanks for your time!
And again, nice job!

**Comment by PitPik** [comment]
Hi @ibsenleo again,

I think I now understand... No, there is no listener for 'onchange' but you can definitely realize this in many different ways. The most performant one would be:

``` javascript
var $myColorPicker = $('#colorpick').colorPicker(); // if that's your starting point
...
var value = 'FF0000';
var colorInstance = $myColorPicker.colorPicker.color;
var colors = colorInstance.colors;

colors.HEX = value; // first set the value in the color model
colorInstance.setColor(null, 'HEX'); // then trigger a color conversion for all colors
$('#colorpick'). // $myColorPicker. or just the selection 
    val('#' + value).
    css({
        'background-color': '#' + colors.HEX,
        'color' : colors.rgbaMixBGMixCustom.luminance > 0.22 ? '#222' : '#ddd'
    });
```

To answer your second question:
No, colorPicker tries to use as little memory as possible, thats why it renders and instantiates the first time it is needed (click on input field) and only has one single shared instance. Unless you really need to see more than 1 colorPicker at a time, you actually never need more instances. If you need more color pickers at a time,... you need to tweak the color picker.

Hope this answers your questions.
Cheers
Peter

**Comment by ibsenleo** [comment]
Hello there! Great!, with this i could modify manually the plugin value. This is what i was looking for. Thanks.
