### ISSUE TITLE
Minified version doens't work with RequireJS

### ISSUE THREAD

**Issue by bronboek** [PitPik/tinyColorPicker#48]
When I use the current jqColorPicker.min.js with RequireJS, something goes wrong:

TypeError: $(...).colorPicker is not a function
$('.input--color').colorPicker({

When I use the seperate colors.js and jqColorPicker.js files, everything is fine. 
Probably the AMD wrapper is wrong in the minified version, can you fix this?

**Comment by PitPik** [comment]
Hi @bronboek,
thanks for this finding.
colors needs to be defined when using in a single file

```
define('colors', [], function () {...
```

The `'colors'` made the difference.
You can now get the latest version and it will work.
Cheers
