### ISSUE TITLE
Dependencies in bower.json

### ISSUE THREAD

**Issue by fschwahn** [PitPik/tinyColorPicker#49]
The jquery dependency is defined as `"jQuery": "^2.2.1"` - first of all, the bower package for jQuery is called `jquery`, not `jQuery` - I'm now pulling in 2 versions of jquery because of this. Secondly, I'm using jquery 1.12.1.1, which is excluded by your version range, but it works just fine. Maybe `>= 1.12.0 < 3.0.0` or something like that would be a better version range, because it would work with older jQuery versions.

**Comment by PitPik** [comment]
Hi @fschwahn,
sorry for the inconvenience ;o)
Fixed it.

**Comment by fschwahn** [comment]
Wow, that was quick, thank you!
