### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by Daijobou** [PitPik/tinyColorPicker#5]
There is a typo in the documentation "buidCallback", should be "buildCallback" ;)

**Comment by PitPik** [comment]
Thanks a lot: I'll fix this asap!

**Comment by Daijobou** [comment]
Great. This is the coolest(simple design, without css) and smallest colorpIcker I found. Very nice work! _praise_

**Comment by PitPik** [comment]
The typo was actually not only in the documentation but all over the place (copy paste ;o)

Thanks again for pointing ou!
