### ISSUE TITLE
First colorPicker popup doesnt hide.

### ISSUE THREAD

**Issue by vshivam** [PitPik/tinyColorPicker#50]
I added two `<a>` elements on a jQuery Mobile page and called colorPicker() on each of them separately. While the color picker popup shows up fine for both the elements, when I click outside the popup, it doesn't hide for the first `<a>`. If I just try the second `<a>`, everything works fine. 

Am I missing something ?

**Comment by PitPik** [comment]
Hi @vshivam ,
I'd be really willing to help you out but with this little information I just can't.
Please use bitPucket or show me some link or even your code so I can see what's going on...
Cheers
Peter

**Comment by vshivam** [comment]
@PitPik Hi!

I was dynamically injecting the colorPicker js and the js was being added to the page twice, once for each `<a>` tag which was probably messing up with some listeners. Once I made sure that the js was being added only once, things were fine.

**Comment by PitPik** [comment]
Great!!
