### ISSUE TITLE
offsetWidth/offsetHeight Deprecated by 4/2016

### ISSUE THREAD

**Issue by jeromystewart** [PitPik/tinyColorPicker#51]
I don't know about other browsers but definitely Chrome .. google advises using object.getBoundingClientRect() and jQuery is following suit by removing osWidth/Height in version 3.0 which should arrive this summer. 

Great plugin, very useful.

**Comment by PitPik** [comment]
As far as I know only SVGElement.offset(Parent|Top|Left|Width|Height) will be deprecated, not on any DOMElement?!? But to make sure, I'll add some fallbacks. Thanks for the hint.
Cheers.
