### ISSUE TITLE
z-cursor postion strangeness 

### ISSUE THREAD

**Issue by jwerre** [PitPik/tinyColorPicker#54]
It looks like z-cursor get's its position from the height and position of the xy-slider. 

https://github.com/PitPik/tinyColorPicker/blob/master/jqColorPicker.js#L186

I'm not sure if this is intentional or a bug but it seems like z-cursor should get its height from z-slider. Otherwise, if z-slider isn't the same height as xy-slider, you end up with things like this:

<img width="236" alt="screen shot 2016-04-18 at 11 34 57 am" src="https://cloud.githubusercontent.com/assets/747587/14615290/c0726d14-0559-11e6-9d37-34bef875f2cf.png">

**Comment by PitPik** [comment]
Hi @jwerre,
yes, this was intentional to keep tinyColorPicker as tiny as possible. I was assuming that the z-slider will aways be as high as xy-slider. Well, I think I will just add this extra line to serve your needs.
Give me some minutes than you can pull the new version from git.

Thanks for your interest,
Cheers,
Peter

**Comment by jwerre** [comment]
Thanks Peter... you're awesome!

**Comment by PitPik** [comment]
@jwerre 
you can pull a new version. Unfortunately it was not only one line to add ;o) Well...
So, if you like tinyColorPicker please don't forget to support it ;o)
Thanks

**Comment by jwerre** [comment]
Happy to support it, please tell me how.

**Comment by PitPik** [comment]
... maybe you want to click the ★ button ;o)

**Comment by jwerre** [comment]
Of course. Do you have a place to donate?

**Comment by PitPik** [comment]
Thank you!!! No, no donations, stars are just fine.
Thanks

**Comment by jwerre** [comment]
You might want to check that last commit. Looks like the xy slider is messed up now.

**Comment by PitPik** [comment]
@jwerre,
What happened? I don't see anything...

**Comment by jwerre** [comment]
@PitPik 
Sorry it's been a while since I've been able to get back to this. It looks like the xy-cursor is still getting its height from the z-slider....

<img width="248" alt="screen shot 2016-04-27 at 1 47 08 pm" src="https://cloud.githubusercontent.com/assets/747587/14867714/afc8f4fc-0c7e-11e6-8983-88f997b1bcf0.png">

**Comment by PitPik** [comment]
Hi @jwerre 
thanks a lot for this finding. This is a quite bad bug, that is only visible when you change dimensions on all sliders (which I didn't do for a long time). I think I have to start writing tests ;o)
I fixed this now in the new version. You don't need to take care of dimension for xy_slider (doesn't have to be 1:1), the z_slider and the alpha_slider any more.
Thanks again
Cheers
