### ISSUE TITLE
Do not close the color piker by clicking on an empty area of the color picker element

### ISSUE THREAD

**Issue by onet4** [PitPik/tinyColorPicker#61]
It would be great if the color picker element does not get closed when an empty area is clicked. 

The demo shows an example of embedded RGB bars. When a user tries to slide the bar, often the picker gets closed by clicking on the empty space between the bars.

A workaround is to insert the following line in the `buildCallback` callback. However, this should be done natively.

``` js
            $elm.on( 'mousedown', function(e) { 
                return false; 
            });
```

**Comment by PitPik** [comment]
Hi @onet4,
this was a bug. Sorry for that.
The new release 1.1.1 takes care of this.

Thanks
