### ISSUE TITLE
how to set color type is Hex ?

### ISSUE THREAD

**Issue by ooing** [PitPik/tinyColorPicker#63]
hi , I am sorry, I am not good at english,
I use tinyColorPicker ,the code is

```
<script>

         $('.color').colorPicker({
            opacity: false,
         }); 
    </script>

```

but  the input show`rgb(xx, x, x)`  I need it  format is `#xxxx`

thanks

**Comment by jwerre** [comment]
```
<input class="color" value="#RRGGBB" >
```

**Comment by ooing** [comment]
@jwerre  but  I think the value of input is empty

**Comment by PitPik** [comment]
Hi @ooing ,
well, there is no real option for default value type yet... I'll definitely add some for the future.
For now you can use a trick to do what you need to do (will work in the future as well).

``` javascript
$('.color').colorPicker(options).each(function(idx, elm) {
    if (!elm.value) {
        $(elm).data('colorMode', 'HEX');
    }
});
```

Thanks for this hint

**Comment by PitPik** [comment]
@ooing ,
another possibility would be to force your value type inside `renderCallback`:

``` javascript
renderCallback: function($elm, toggled) {
    var colors = this.color.colors; // the whole color object

    $elm.val('#' + colors.HEX);
}
```

**Comment by ooing** [comment]
@PitPik  thanks.

**Comment by BillBushee** [comment]
If you need to be able to set a color field back to null you can check $elm.val() before setting the value as HEX.

renderCallback: function($elm, toggled) {
    if ($elm.val()) {
        var colors = this.color.colors; // the whole color object
        $elm.val('#' + colors.HEX);
    }
}
