### ISSUE TITLE
'change' event

### ISSUE THREAD

**Issue by fi5hbrains** [PitPik/tinyColorPicker#65]
Sorry, my JS knowledge is not enough to solve this.

How can I trigger 'change' event for the input field every time I pick a colour? When I add a render callback: "$elm.trigger('change')" or "$elm.click()", it says: "Maximum call stack size exceeded".

Thank you.

**Comment by fi5hbrains** [comment]
Oh, i see. triggering "change" triggers the whole thing over again. Never mind then. I found a way around. Thanks for the awesome plugin. It is the best.

**Comment by PitPik** [comment]
Hi @fi5hbrains 

good luck!!!
