### ISSUE TITLE
Color 'none' and 'transparent' color

### ISSUE THREAD

**Issue by jimmyphong** [PitPik/tinyColorPicker#66]
In my app write with php and echo color value to input as default ! so how to i set 'none' or 'transparent' color to input.

When using 'none' or 'transparent' value , focus input show #NANNANNAN

**Comment by PitPik** [comment]
Hi @jimmyphong ,
this is the same issue as in issue #60. tinyColorPicker can only work with HEX, rgb(a) and hsl(a).

If you need to send different values to the server or need to display things differently then standard for colorPicker then you need to use `renderCallback` to do so.

Cheers :)
