### ISSUE TITLE
ColorPicker panel is not in a correct position.

### ISSUE THREAD

**Issue by carldai0106** [PitPik/tinyColorPicker#69]
Thanks for your color picker.
![image](https://cloud.githubusercontent.com/assets/12929041/17431191/5d91cafa-5b2b-11e6-9fa0-c563e069909c.png)
I think there is a bug. When the input is in bottom of the page, color picker is not in a correct position.
It can perceive its own position and show it to the top of the input.

**Comment by PitPik** [comment]
Hi @carldai0106,
well, this is not a bug but I skipped this feature as it's mostly not used, and if, easy to compensate:
There is a callback `positionCallback($UI);` with `this` as the instance of colorPicker. So you can have access to the `this.$input`, the input fields and `$UI`, the colorPicker `<div>` itself.
So you can make your own positioning algorithm as you need it. `this.$UI` even holds the `_width` and `_height` of the color picker for faster access. Look at `./demo/index.js` on line 66 where I made a copy of the internal mechanism. This could be a start-point for you to make it move wherever it should.

I hope this helped.
Cheers

**Comment by carldai0106** [comment]
Hi @PitPik 
Thank you very much.
