### ISSUE TITLE
Box not disappear

### ISSUE THREAD

**Issue by Daijobou** [PitPik/tinyColorPicker#7]
Go to http://www.dematte.at/tinyColorPicker/ click on first input, the box is open. Now click on box with example code under the box. the box not disappear, its moving to grey example box.

See here: http://picload.org/image/cwcidrr/bugcolorpickera.png
EDIT: Go to http://www.dematte.at/tinyColorPicker/  and click only on grey box. the colorpicker will appear. why?

Here more: http://jsfiddle.net/030j27LL/
Click on a input field and try to close the box. its only working with click above the box. Not left, right or bottom the box.

**Comment by PitPik** [comment]
This was done on purpose... have you tried to adjust the color picker after clicking on the gray code-box? You can actually change the background color... in the index.html file there is a `$('pre').colorPicker({doRender: false});` that makes it possible... and this also demonstrates that the colorPicker stays in the view: The `pre` is now the input box and if the colorPicker doesn't fit in the view, it scrolls into view. As soon as you scroll down enough, it stays on the lower edge of the gray box.

**Comment by Daijobou** [comment]
@gray codebox
Oh.. cool! :)

But take a look in my last comment
http://jsfiddle.net/030j27LL/ 
Click on a input field and try to close the box. its only working with click above the box. Not left, right or bottom the box.

**Comment by PitPik** [comment]
It is possible to close it at the sides, but only if you stay within the body. Your body there is as high as the last `<div id="debug-b"></div>`. if you set `html, body {height: 100%}` in your css then you're fine.

**Comment by Daijobou** [comment]
Yes, you are right. Its a problem with jsfiddle, not tinyColorPicker.
