### ISSUE TITLE
Can't change default opacity

### ISSUE THREAD

**Issue by activestylus** [PitPik/tinyColorPicker#74]
For some reason the picker always defaults to 0.5 opacity, even when I disable the option

```
$('input.colorpicker').colorPicker({ opacity: false, alpha: 1 })
```

As you can see I tried setting the alpha option but it ALWAYS defaults to 0.5

How do I fix this?

**Comment by PitPik** [comment]
Hi @activestylus , 
it's not easy to understand your problem when I don't see your setup. I need to know what value your input field has or what background color...
But if I have to guess: the option ```alpha``` doesn't exist, so it also doesn't do anything but there is ```opacity``` that just defines if the opacity slider will be rendered and ```forceAlpha``` where you can prevent the alpha to be set when set to ```false```.

**Comment by activestylus** [comment]
`forceAlpha` was exactly what I needed. Thanks!
