### ISSUE TITLE
Suggestion: Setting z-index when opening colorPicker

### ISSUE THREAD

**Issue by patschi** [PitPik/tinyColorPicker#75]
I recently stumbled about an issue that the colorPicker was not visible when opening an overlay the second time (because of the own implementation of the modal windows). After further investigation I came about the idea to set z-index and voila, the colorPicker is visible again. I workaround'ed the issue by using now:

```
$("input[name=color]").colorPicker({ opacity: false, cssAddon: '.cp-color-picker{z-index:1000;}' });
```

Maybe it would be a good idea to prevent issues with visibility by always setting z-index quite high.

**Comment by PitPik** [comment]
Hi @patschi ,
thanks for your participation and interest in tinyColorPicker.
Your solution is actually perfect if you have to deal with z-index.
I prefer not to initially set a z-index as I'm definitely not a friend of z-index at all (it is like using setTimeout, once you begin with it you can never stop again and produce a lot of chaos... and you also never know what other components also use a z-index,... and how high).
If you encounter trouble with z-index in your page/application then you should rather reconsider your design and layout.
The colorPicker appends itself on the bottom of the document, so it should be above all other things on the page already, not using any z-index. But if you have other components using z-index, adding a z-index to colorPicker, like you did, is just perfectly fine.
