### ISSUE TITLE
Set initial color

### ISSUE THREAD

**Issue by vanowm** [PitPik/tinyColorPicker#78]
Reading the instructions I don't understand how do we set initial color using options. And how do we change initial color during renderCallback on show event?

Using
```
	renderCallback: function($elm, toggled) {
		// on show
		if( toggled == true ){
			this.color.setColor("#0000FF");
		}
  }
```
Doesn't do anything.

**Comment by PitPik** [comment]
Hi @vanowm ,
I don't really understand what colour you want to set (and when and why).
Could you please tell me what you want to achieve, maybe I can give you some instructions...

**Comment by vanowm** [comment]
I want to "attach" the same tcp to different buttons on website. Because only one colorpicker is "allowed" to be opened at any time, I just move it from one button to another when user clicks a button.
What I was looking for was ability set a color that tcp will show when opened, which depends on the button it was opened from.
The instructions doesn't seem to address situations how to set default color dynamically upon opening tcp or even when it's already opened (hell it doesn't even show how to set default color during initialization!).

So far it seems using ```this.color.setColor()``` actually works, but it doesn't show the new default color, for that ```this.render()``` must be executed afterwards.
```Javascript
	renderCallback: function($elm, toggled) {
		// on show
		if( toggled == true ){
			this.color.setColor("#0000FF");
			this.render();
		}
  }
```
Finally, just out of curiosity, if I don't have access to pickerObj, is there a way access already initialized tcp?

**Comment by PitPik** [comment]
Hi @vanowm again,
well, the buttons on the test page (http://www.dematte.at/tinyColorPicker/) show how to do that (actually also the input fields). They are not buttons but DIVs but work like all other elements, so also buttons (shown also by the input fields):
You can put attributes to all kinds of DOMElements, even if they would't make sense. In this case we're talking about the attribute "value". 
So, if you put a value on your button:
```
<button value="#999999">Hello</button>
```
then tcp will pick it up automatically. So no need for javascript interaction.
If there is no value present, it will take the background color if any is set. (On the demo page you can see that if clicking on the gray boxes showing the code parts, there also appears a color picker that changes the color of the box. So the color picker takes the value from the background color...)
If this is also not the case, it will assume #fff as the standard.

So, if you want anything being picked up by tcp, set a value to the element...

**Comment by PitPik** [comment]
"Finally, just out of curiosity, if I don't have access to pickerObj, is there a way access already initialized tcp?"

Well, I guess not, not that I can think of. Why would you need that?

**Comment by vanowm** [comment]
Website that uses tcp incorrectly sets default color and incorrectly saves new color via renderCallback function. I'm trying fix it with userscript.
Website initializes tcp via anonymous function therefore not accessible via userscript.

**Comment by PitPik** [comment]
Ok, I see...
You have to understand that the colorPicker is not responsible for the color value when clicking or focusing an item on the page. ColorPicker just picks up the value when opened and presents it. Then, when UI is used, it changes the value (you actually don't need the renderCallback, it does that by default).
So, don't try to make the colorPicker do something, just update the value.
```
$('.color').val('#999');
```
That's how you would fix wrongly initialized items.
