### ISSUE TITLE
Close with escape button

### ISSUE THREAD

**Issue by vanowm** [PitPik/tinyColorPicker#79]
Would be nice have an options to close CP with escape button.

**Comment by PitPik** [comment]
```
$(document.body).on('keydown', function(e) {
    if (e.which == 27) {
        $(this).mousedown();
    }
});
```

**Comment by vanowm** [comment]
Wouldn't this trigger mousedown even when tcp is closed?

**Comment by PitPik** [comment]
Yes, it would, but I wouldn't care too much about it.
If it bothers you too much then you can also do the following:
```javascript
$('.color')
.colorPicker() // maybe you also pass some options here...
.on('keydown', function(e) {
    if (e.which == 27) {
        $(document.body).mousedown();
        $(this).blur();
    }
});
```

Let me know if this helps,
Cheers

**Comment by vanowm** [comment]
Thank you. In my tests that didn't work unless I attach keydown event to the body as per your first example.

Another method seems to be working without using mousedown is set keydown event inside buildCallback were we have access to colorPicker object function:

```Javascript
$('.color').colorPicker(
{
	buildCallback: function($elm)
	{
		let tcp = this;
		$("body").on("keydown", function(e)
		{
			if (e.which == 27 && $elm.is(":visible"))
				tcp.toggle();
		});
	}
})
```

Alternatively if colorPicker object returned by colorPicker() function is available it can be used too:

```Javascript
var colorPickerObject = $('.color').colorPicker();
$("body").on("keydown", function(e)
{
	if (e.which == 27 && $(colorPickerObject.colorPicker.$UI).is(":visible"))
		colorPickerObject.colorPicker.toggle();
});

```

Is there any issues with these methods?
