### ISSUE TITLE
Value with auto-correct?

### ISSUE THREAD

**Issue by Daijobou** [PitPik/tinyColorPicker#83]
I have a input with value "#444". colorpicker set the background color in input field, but not change value from "#444" to "#444444". This happen after click in input. Maybe this should happen with init?

**Comment by PitPik** [comment]
Hi @Daijobou ,
thanks for your participation. =)
Well, this bug report is based on expectations, not on an actual bug (unless you find the documentation say something different).
One benefit of tinyColorPicker is that it doesn't initialise until you start using it, so no memory usage, no scripts running,... until it is actually being used. This makes initial page render faster as there is no JS calculations done on build (other more important scripts may use those resources, like MVC, ...)
If you though need this to happen, use the ```buildCallback()``` or jQuery to do this job.

Good luck with your project.
Cheers.

**Comment by Daijobou** [comment]
I think you are right. Thank you! :)
